### ISSUE TITLE
如何居中一个div呢？

### ISSUE THREAD

**Issue by Sphinm** [suminhohu/suminhohu.github.io#13]
居中是我们经常见到的一个东东，也分为水平居中和垂直居中或者两个同时要满足，以下就是几种我常用到的，如果你有更好的也请告诉我！

一、水平居中：给div设置一个宽度，然后添加margin:0 auto属性
```css
div {
	width: 200px;
	margin: 0 auto;
	background-color: pink;
	/* 方便看效果 */
}
```

二、让绝对定位的div居中
```css
 div {
 	position: absolute;
 	width: 300px;
 	height: 300px;
 	margin: 0 auto;
 	top: 0;
 	left: 0;
 	bottom: 0;
 	background-color: pink;	/* 方便看效果 */
 }
```
三、水平垂直居中（一）
```css
 div {
 	position: absolute;		/* 相对定位或绝对定位均可 */
 	width:300px;
 	height:300px;
 	top: 50%;
 	left: 50%;
 	margin: -150px 0 0 -150px;     	/* 外边距为自身宽高的一半 */
 	background-color: pink;	 	/* 方便看效果 */
  }
```

四、水平垂直居中（二）
```css
 div {
 	position: absolute;		/* 相对定位或绝对定位均可 */
 	width:500px;
 	height:300px;
 	top: 50%;
 	left: 50%;
 	transform: translate(-50%, -50%);
 	background-color: pink;	 	/* 方便看效果 */
 }
```
五、水平垂直居中（三）
```css
 利用 flex 布局
 实际使用时应考虑兼容性

 .container {
 	display: flex;
 	align-items: center; 		/* 垂直居中 */
 	justify-content: center;	/* 水平居中 */
 }
 .container div {
 	width: 100px;
 	height: 100px;
 	background-color: pink;		/* 方便看效果 */
 }  
```
